### ISSUE TITLE
Invalid end date for permanent bans

### ISSUE THREAD

**Issue by Trikolon** [Tallcraft/tc-players#3]
The unban date is invalid if `expiresAt` is null. It shows "1/1/1970" = unix 0.

**Comment by metype** [comment]
May I have the link to a player profile showing this bug so I can debug?

**Comment by Trikolon** [comment]
Here is an example: https://players.tallcraft.com/player/81ef35d4-839b-4e72-85ae-edad87aabe12
The player has been unbanned, thus the expireAt timestamp is `null`.

**Comment by metype** [comment]
While I do see that having a non-active ban with a 'Never' expiry date may look odd, this is working as intended, the API does not reveal an unban date to infractions, just the date the ban was set to expire at, so I have no way to, for example, show when the ban actually ended if the user was unbanned, the only thing I can display is the end date set for the original ban. And a permanent ban and a 'null' expiresAt aren't possible to tell apart. If I am misunderstanding what you're getting at, just tell me.

**Comment by Trikolon** [comment]
Can't we just label the field with `-` if the value is `null`? Right now we're trying to parse a date from `null` which results in a UNIX = 0 Date object.

**Comment by Trikolon** [comment]
Here is the object with the null field:
```
{
	"data": {
		"player": {
			"lastSeenName": "Bappo_on_cracko",
			"uuid": "81ef35d4-839b-4e72-85ae-edad87aabe12",
			"lastLogin": "1599098429000",
			"firstLogin": "1598497442000",
			"groups": [],
			"connectedTo": null,
			"infractions": {
				"bans": [
					{
						"reason": "NSFW",
						"isActive": false,
						"staffName": "Ravadosh",
						"server": {
							"name": "TC Network",
							"__typename": "MCServer"
						},
						"createdAt": "1598637668000",
						"expiresAt": null,
						"__typename": "PlayerBan"
					}
				],
				"__typename": "PlayerInfractions"
			},
			"__typename": "Player"
		}
	}
}
```
